### ISSUE TITLE
Nullbot strategy doesn't match research target/progress

### ISSUE THREAD

**Issue by adrian5** [haoNoQ/nullbot#13]
This might not be a bug, but when playing coop with Nullbot, I noticed that `"mc" personality + "mg" research` seems to quickly move to cannons as the weapon of choice, even if machine guns are way ahead in research progress. At the same time, `"mc" personality + "mo" research` seems to prefer machine guns, even if cannons are way ahead in progress.

I don't know if anything can be done about this, maybe Nullbot doesn't take research progress into account and makes up its own mind. It's just strange that it appears to be coaxed into a certain direction by the research setting I give it – alas the wrong direction.

**Comment by haoNoQ** [comment]
Hmm, yep. That needs thinking.

Assuming my understanding is correct:

NullBot would prefer cannons when he has them (researched *and* on the personality's list of choices) when the opponent throws tanks at him, simply because cannons are better against tanks, regardless of whether he was said to avoid researching them, regardless of progress on the branches (generally, he doesn't have a well-defined notion of research progress or research branch).

Currently chat commands only control research paths ("hey help me out with this machinegun tech, and i'll do the cannons for you" is how it works), but not weapon choices ("hey we're going pure machineguns, you shouldn't care that he's on full tracks and they do no damage, we'd beat him through pure upgrades anyway" is not what the chat command means). I'm not sure if this latter approach is worth implementing - as the possibility to beat the enemy with an unbalanced army (eg. pure machineguns) is essentially a flaw in the game; i removed the mg-flamer sub-personality from NullBot3 for a similar reason - all it did was exploit the incendiary damage bug, which was so bad it was a valid option for competitive play, but not fun at all for seeing AI do this.

So, generally, as far as i remember, chat commands for technologies shouldn't affect weapon choices at all. The AI just sticks to whatever would, provided uniform research, work best against what the opponent has, which may be different in different games. If the enemy is NullBot as well, there might also be a feedback loop that'd explain the correlation you observe - depending on what units you have the enemy would make different choices, which would lead your ally to make different choices. NullBot3's adaptation produces a lot of such emergent behavior, often weird.

It also might be that there's a bug somewhere and my understanding is not correct and chat commands actually have this effect.

**Comment by adrian5** [comment]
I see, thanks for the elaborate insight!

> If the enemy is NullBot as well, there might also be a feedback loop that'd explain the correlation you observe (…)

Yes, that might have something to do with my observations. Alright, keep up the good work – it's an amazing AI that's hard to beat and blows the socks off Nexus.
